files: "^sqlelixir"
repos:
- repo: "https://github.com/pre-commit/pre-commit-hooks"
  rev: "v3.2.0"
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-added-large-files
- repo: local
  hooks:
  - id: black
    name: black
    types: [python]
    language: system
    entry: poetry run black --quiet --check --diff --target-version=py310
  - id: flake8
    name: flake8
    types: [python]
    language: system
    entry: poetry run flake8 --show-source --select=C,E,F,W,B,B950 --ignore=B009,E203,B306,E501,W503 --max-line-length=80
